graph TD;
Tree(Gamal )
Tree_Camal(Camal Emad )
Tree --> Tree_Camal
Tree_Camal_Ahmed(Ahmed Basem )
Tree_Camal --> Tree_Camal_Ahmed
Tree_Camal_Camal(Camal Dawood )
Tree_Camal --> Tree_Camal_Camal
Tree_Camal_Emad(Emad Fady )
Tree_Camal --> Tree_Camal_Emad
Tree_Ibrahim(Ibrahim Khaled )
Tree --> Tree_Ibrahim
Tree_Ibrahim_Gamal(Gamal Hassan )
Tree_Ibrahim --> Tree_Ibrahim_Gamal
Tree_Ibrahim_Ibrahim(Ibrahim Jack )
Tree_Ibrahim --> Tree_Ibrahim_Ibrahim
Tree_Ibrahim_Khaled(Khaled )
Tree_Ibrahim --> Tree_Ibrahim_Khaled
