graph TD;
Tree(Fady, Jack)
Tree_Camal(Camal)
Tree --> Tree_Camal
Tree_Camal_Ahmed(Ahmed, Basem)
Tree_Camal --> Tree_Camal_Ahmed
Tree_Camal_Camal(Camal)
Tree_Camal --> Tree_Camal_Camal
Tree_Fady(Fady)
Tree --> Tree_Fady
Tree_Fady_Dawood(Dawood, Emad)
Tree_Fady --> Tree_Fady_Dawood
Tree_Fady_Fady(Fady, Ibrahim)
Tree_Fady --> Tree_Fady_Fady
Tree_Jack(Jack)
Tree --> Tree_Jack
Tree_Jack_Hassan(Hassan)
Tree_Jack --> Tree_Jack_Hassan
Tree_Jack_Jack(Jack, Khaled)
Tree_Jack --> Tree_Jack_Jack
